### PR TITLE
get the sdk path to find the executable on linux

### PR DESCRIPTION
**Pull request by lyonbeckers**
The method for running the PlaydateSimulator on Linux assumes that it's in your PATH. The desktop file that gets set up from the setup.sh script in the linux Playdate SDK just executes it from the SDK path, so I figure it's probably safe to do it the same way

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
Could we maybe have it try to execute `PlaydateSimulator` first and if that fails, then fallback to trying something based on the SDK path on all platforms?

This change would break running the simulator from crank on my system, but I admittedly have an uncommon setup so I can judt patch crank or work around this if generalizing this behavior is undesired by the maintainers

**Comment by lyonbeckers** [comment]
I think that's a good idea, I was considering making this change for all platforms, but noticed both Windows and Mac get some kind of installer, so I assumed there's less variability in the way the environments might be set up. I haven't tried the SDK on either Mac or Windows so I wasn't sure. I'll try a fallback for this cfg in the meantime

**Comment by boozook** [comment]
> error: the feature `lang_items` is internal to the compiler or standard library

This is something new. Did I miss something? Is this feature was renamed or denied somehow? 🤔

**Comment by boozook** [comment]
LGTM, but what about [error on CI]? 🙄

[error on CI]: https://github.com/pd-rs/crank/actions/runs/5772547705/job/15657415474?pr=45#step:9:121

**Comment by lyonbeckers** [comment]
Looks like it might be something new on nightly, I found this tracking issue for adding an internal_features lint, and based on the error message, it sounds like it's set to deny by default
https://github.com/rust-lang/compiler-team/issues/596

**Comment by boozook** [comment]
Looks like we're using stable toolchain instead of just [installed](https://github.com/pd-rs/crank/actions/runs/5772547705/job/15657415474?pr=45#step:3:51) nightly.

**Comment by boozook** [comment]
Seems to you're right 🙄

**Comment by lyonbeckers** [comment]
Updated on my machine, then tried adding an #![allow(internal_features)] to crankstart's lib.rs but that doesn't seem to have done it for me 😬

**Comment by boozook** [comment]
Looks like fixed:
- [job](https://github.com/pd-rs/crank/actions/runs/5777521340/job/15657792636?pr=47)
- [PR](https://github.com/pd-rs/crankstart/pull/49)

**Comment by boozook** [comment]
@lyonbeckers @lilyinstarlight [important message](https://github.com/pd-rs/crankstart/pull/49#issuecomment-1666907538)

**Review by boozook — APPROVED** [review]

**Pull request merged**
