### PR TITLE
Fix ARM compiler path on Windows

### PR DESCRIPTION
**Pull request by parasyte**
Looks like the compiler path changed in recent versions. I'm using Version `12.3.Rel1`, released July 28, 2023.

https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

Possible fix for #44?

### CODE REVIEW

**Comment by parasyte** [comment]
Should this path really be hardcoded? Assuming the toolchain installer sets your path correctly, and it does in my case, this absolute path can just be removed, and the environment relied on. Doing this would be more robust since there will be no need to update `crank` in lockstep with the compiler toolchain.

**Comment by boozook** [comment]
This looks like kinda breaking change for old versions and system without arm-gcc in the PATH. That's ok, but so need to bump minor version component.
Also as I see there's new problems with unix on CI.

**Review by boozook — CHANGES_REQUESTED** [review]
Okay, that's ok, but I'm sure there also need to mention in the readme that arm-gcc should be in path on windows.

**Comment by boozook** [comment]
Also, how about use my new [utils](https://github.com/boozook/playdate/tree/main/support/utils) to find gcc? [Here is example](https://github.com/boozook/playdate/blob/6ab6ef984f853ed9c5c7c18c4e8ace73ec254934/support/utils/src/toolchain/gcc.rs#L378).

**Comment by parasyte** [comment]
WRT the new stuff, I'm going to have to migrate to it. When I started my project, none of that was even publicly available.

**Comment by parasyte** [comment]
Oh look, this fixes the broken Windows test, lol. :tada:

Yeah, I can update the readme.

**Review by boozook — APPROVED** [review]

**Review by boozook — APPROVED** [review]

**Pull request merged**
